#!/bin/sh

check_if_installed() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "$1 not installed" >&2
    exit 1
  fi
}

check_if_installed tc
check_if_installed ipset

case "$1" in
  init)
    # Limits in KB/s
    download_limit="${MTC_DL_LIMIT:-347}"
    upload_limit="${MTC_UL_LIMIT:-59}"

    for dev in wlan0 wlan1; do
      tc qdisc add dev "$dev" root handle 1: htb default 12
      tc class add dev "$dev" parent 1: classid 1:1 htb rate 100mbit ceil 100mbit
      tc class add dev "$dev" parent 1:1 classid 1:10 htb rate "${download_limit}kbps" ceil "${download_limit}kbps"
      tc class add dev "$dev" parent 1:1 classid 1:11 htb rate 100mbit ceil 100mbit
    done

    tc qdisc add dev eth0 root handle 1: htb default 12
    tc class add dev eth0 parent 1: classid 1:1 htb rate 100mbit ceil 100mbit
    tc class add dev eth0 parent 1:1 classid 1:10 htb rate "${upload_limit}kbps" ceil "${upload_limit}kbps"
    tc class add dev eth0 parent 1:1 classid 1:11 htb rate 100mbit ceil 100mbit

    # Set up filters to send marked packets to the slow flow
    for dev in wlan0 wlan1 eth0; do
      tc filter add dev "$dev" protocol ip parent 1: prio 1 handle 6 fw flowid 1:10
    done

    ipset new mtc hash:ip

    iptables -t mangle -A fwmark -j CONNMARK --restore-mark
    iptables -t mangle -A fwmark -m mark ! --mark 0 -j ACCEPT
    iptables -t mangle -A fwmark -m set --match-set mtc src -j MARK --set-mark 6

    iptables -t mangle -A POSTROUTING -j CONNMARK --save-mark
  ;;

  clear|flush)
    ipset flush mtc
  ;;

  halt|kill)
    for dev in wlan0 wlan1 eth0; do
      tc qdisc del dev "$dev" root 
    done

    # Assumes my script will be the only thing editing these chains
    iptables -t mangle -F fwmark
    iptables -t mangle -F POSTROUTING

    ipset destroy mtc
  ;;

  help)
    echo "Usage: mtc COMMAND|IPV4-ADDRESS"
    echo
    echo "Commands:"
    echo "  init      - initialise setup, adding qdiscs, iptables rules, etc.; to be ran before adding IPv4 address filters."
    echo "              Specifying the environment variables MTC_DL_LIMIT and MTC_UL_LIMIT in KB/s allows customisation of the"
    echo "              default limits."
    echo "  clear     - wipe the IPv4 addresses being throttled."
    echo "  halt|kill - deinitialise setup, removing all qdiscs and iptables rules."
    echo "  help      - display this help snippet."
  ;;

  *) # Assumes argument is an IPv4 address
    ipset add mtc "$1"
  ;;
esac
